# Trio exome pipeline. Rules get added one step at a time.
configfile: "config/config.yaml"

SAMPLES = list(config["samples"])

rule all:
    input:
        expand("data/trimmed/{sample}_R1.fastq.gz", sample=SAMPLES),
        expand("results/align/{sample}.bam", sample=SAMPLES),
        expand("results/align/{sample}.bam.bai", sample=SAMPLES),
        expand("results/qc/align/{sample}.flagstat.txt", sample=SAMPLES),
        expand("results/qc/align/{sample}.target_qc.tsv", sample=SAMPLES),
        "results/qc/multiqc/multiqc_report.html",
        expand("data/{sample}.chr22.bam", sample=SAMPLES),
        "results/benchmark/HG002_chr22",

rule fastp:
    input:
        r1="data/fastq/{sample}_R1.fastq.gz",
        r2="data/fastq/{sample}_R2.fastq.gz",
    output:
        r1="data/trimmed/{sample}_R1.fastq.gz",
        r2="data/trimmed/{sample}_R2.fastq.gz",
        json="results/qc/fastp/{sample}.json",
        html="results/qc/fastp/{sample}.html",
    threads: 4
    shell:
        "fastp -i {input.r1} -I {input.r2} -o {output.r1} -O {output.r2} "
        "--detect_adapter_for_pe -w {threads} -j {output.json} -h {output.html}"


rule align:
    input:
        r1="data/trimmed/{sample}_R1.fastq.gz",
        r2="data/trimmed/{sample}_R2.fastq.gz",
        ref=config["reference_fasta"],
        idx=multiext(config["reference_fasta"], ".amb", ".ann", ".bwt", ".pac", ".sa"),
    output:
        bam="results/align/{sample}.bam",
    params:
        rg=lambda wc: f"@RG\\tID:{wc.sample}\\tSM:{wc.sample}\\tPL:ILLUMINA\\tLB:{wc.sample}_lib1\\tPU:AC7F6GANXX.L008",
    threads: 4
    shell:
        "bwa mem -t {threads} -R '{params.rg}' {input.ref} {input.r1} {input.r2} "
        "| samtools fixmate -m -u - - "
        "| samtools sort -u -@ {threads} - "
        "| samtools markdup -@ {threads} - {output.bam}"

rule index_bam:
    input:
        "results/align/{sample}.bam",
    output:
        "results/align/{sample}.bam.bai",
    shell:
        "samtools index {input}"


rule flagstat:
    input:
        "results/align/{sample}.bam",
    output:
        "results/qc/align/{sample}.flagstat.txt",
    shell:
        "samtools flagstat {input} > {output}"


rule target_qc:
    input:
        bam="results/align/{sample}.bam",
        bai="results/align/{sample}.bam.bai",
        bed=config["target_bed"],
        script="workflow/scripts/target_qc.sh",
    output:
        "results/qc/align/{sample}.target_qc.tsv",
    shell:
        "bash {input.script} {wildcards.sample} {input.bam} {input.bed} > {output}"


rule fastqc:
    input:
        "data/fastq/{sample}_{read}.fastq.gz",
    output:
        html="results/qc/fastqc/{sample}_{read}_fastqc.html",
        zip="results/qc/fastqc/{sample}_{read}_fastqc.zip",
    threads: 2
    shell:
        "fastqc -t {threads} -o results/qc/fastqc {input}"


rule multiqc:
    input:
        expand("results/qc/fastqc/{sample}_{read}_fastqc.zip", sample=SAMPLES, read=["R1", "R2"]),
        expand("results/qc/fastp/{sample}.json", sample=SAMPLES),
        expand("results/qc/align/{sample}.flagstat.txt", sample=SAMPLES),
    output:
        "results/qc/multiqc/multiqc_report.html",
    shell:
        "multiqc {input} -o results/qc/multiqc -f"

rule subset_bam:
    output:
        bam="data/{sample}.chr22.bam",
        bai="data/{sample}.chr22.bam.bai",
    params:
        url=lambda wc: config["samples"][wc.sample]["bam_url"],
        region=config["region"],
    shell:
        "samtools view -b -o {output.bam} '{params.url}' {params.region} && "
        "samtools index {output.bam}"


rule bam_to_fastq:
    input:
        "data/{sample}.chr22.bam",
    output:
        r1="data/fastq/{sample}_R1.fastq.gz",
        r2="data/fastq/{sample}_R2.fastq.gz",
        singletons="data/fastq/{sample}_singletons.fastq.gz",
    shell:
        "samtools collate -u -O {input} "
        "| samtools fastq -n -F 0x900 -1 {output.r1} -2 {output.r2} -0 /dev/null -s {output.singletons} -"


rule haplotype_caller:
    input:
        bam="results/align/{sample}.bam",
        ref=config["reference_fasta"],
    output:
        gvcf="results/variants/{sample}.g.vcf.gz",
        idx="results/variants/{sample}.g.vcf.gz.tbi",
    params:
        region=config["region"],
    shell:
        "gatk HaplotypeCaller -R {input.ref} -I {input.bam} -O {output.gvcf} -ERC GVCF -L {params.region}"

rule combine_gvcfs:
    input:
        gvcfs=expand("results/variants/{sample}.g.vcf.gz", sample=config["samples"].keys()),
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.g.vcf.gz",
    params:
        region=config["region"],
        variant_args=lambda wc, input: " ".join(f"-V {g}" for g in input.gvcfs),
    shell:
        "gatk CombineGVCFs -R {input.ref} {params.variant_args} -O {output} -L {params.region}"
    
rule genotype_gvcfs:
    input:
        gvcf="results/variants/trio.g.vcf.gz",
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.vcf.gz",
    params:
        region=config["region"],
    shell:
        "gatk GenotypeGVCFs -R {input.ref} -V {input.gvcf} -O {output} -L {params.region}"

rule select_snps:
    input:
        vcf="results/variants/trio.vcf.gz",
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.snps.vcf.gz",
    shell:
        "gatk SelectVariants -R {input.ref} -V {input.vcf} --select-type-to-include SNP -O {output}"
    
rule select_indels:
    input:
        vcf="results/variants/trio.vcf.gz",
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.indels.vcf.gz",
    shell:
        "gatk SelectVariants -R {input.ref} -V {input.vcf} --select-type-to-include INDEL -O {output}"

rule filter_snps:
    input:
        vcf="results/variants/trio.snps.vcf.gz",
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.snps.filtered.vcf.gz",
    shell:
        "gatk VariantFiltration -R {input.ref} -V {input.vcf} -O {output} "
        "--filter-expression 'QD < 2.0' --filter-name QD2 "
        "--filter-expression 'FS > 60.0' --filter-name FS60 "
        "--filter-expression 'MQ < 40.0' --filter-name MQ40 "
        "--filter-expression 'MQRankSum < -12.5' --filter-name MQRankSum-12.5 "
        "--filter-expression 'ReadPosRankSum < -8.0' --filter-name ReadPosRankSum-8 "
        "--filter-expression 'SOR > 3.0' --filter-name SOR3"

rule filter_indels:
    input:
        vcf="results/variants/trio.indels.vcf.gz",
        ref=config["reference_fasta"],
    output:
        "results/variants/trio.indels.filtered.vcf.gz",
    shell:
        "gatk VariantFiltration -R {input.ref} -V {input.vcf} -O {output} "
        "--filter-expression 'QD < 2.0' --filter-name QD2 "
        "--filter-expression 'FS > 200.0' --filter-name FS200 "
        "--filter-expression 'ReadPosRankSum < -20.0' --filter-name ReadPosRankSum-20 "
        "--filter-expression 'SOR > 10.0' --filter-name SOR10"

rule merge_filtered:
    input:
        snps="results/variants/trio.snps.filtered.vcf.gz",
        indels="results/variants/trio.indels.filtered.vcf.gz",
    output:
        "results/variants/trio.filtered.vcf.gz",
    shell:
        "gatk MergeVcfs -I {input.snps} -I {input.indels} -O {output}"

rule benchmark:
    input:
        vcf="results/variants/trio.filtered.vcf.gz",
        truth_vcf=config["truth_vcf"],
        regions=config["eval_regions"],
        sdf=config["rtg_sdf"],
    output:
        directory("results/benchmark/HG002_chr22"),
    params:
        sample="HG002",
    shell:
        "rm -rf {output} && rtg vcfeval -b {input.truth_vcf} -c {input.vcf} -t {input.sdf} -o {output} "
        "--bed-regions {input.regions} --sample {params.sample}"