# Trio exome pipeline. Rules get added one step at a time.
configfile: "config/config.yaml"

SAMPLES = list(config["samples"])

rule all:
    input:
        expand("data/trimmed/{sample}_R1.fastq.gz", sample=SAMPLES),
        expand("results/align/{sample}.bam", sample=SAMPLES),
        expand("results/align/{sample}.bam.bai", sample=SAMPLES),
        expand("results/qc/align/{sample}.flagstat.txt", sample=SAMPLES),
        expand("results/qc/align/{sample}.target_qc.tsv", sample=SAMPLES),
        "results/qc/multiqc/multiqc_report.html",
                expand("data/{sample}.chr22.bam", sample=SAMPLES),

rule fastp:
    input:
        r1="data/fastq/{sample}_R1.fastq.gz",
        r2="data/fastq/{sample}_R2.fastq.gz",
    output:
        r1="data/trimmed/{sample}_R1.fastq.gz",
        r2="data/trimmed/{sample}_R2.fastq.gz",
        json="results/qc/fastp/{sample}.json",
        html="results/qc/fastp/{sample}.html",
    threads: 4
    shell:
        "fastp -i {input.r1} -I {input.r2} -o {output.r1} -O {output.r2} "
        "--detect_adapter_for_pe -w {threads} -j {output.json} -h {output.html}"


rule align:
    input:
        r1="data/trimmed/{sample}_R1.fastq.gz",
        r2="data/trimmed/{sample}_R2.fastq.gz",
        ref=config["reference_fasta"],
        idx=multiext(config["reference_fasta"], ".amb", ".ann", ".bwt", ".pac", ".sa"),
    output:
        bam="results/align/{sample}.bam",
    params:
        rg=lambda wc: f"@RG\\tID:{wc.sample}\\tSM:{wc.sample}\\tPL:ILLUMINA\\tLB:{wc.sample}_lib1\\tPU:AC7F6GANXX.L008",
    threads: 4
    shell:
        "bwa mem -t {threads} -R '{params.rg}' {input.ref} {input.r1} {input.r2} "
        "| samtools fixmate -m -u - - "
        "| samtools sort -u -@ {threads} - "
        "| samtools markdup -@ {threads} - {output.bam}"

rule index_bam:
    input:
        "results/align/{sample}.bam",
    output:
        "results/align/{sample}.bam.bai",
    shell:
        "samtools index {input}"


rule flagstat:
    input:
        "results/align/{sample}.bam",
    output:
        "results/qc/align/{sample}.flagstat.txt",
    shell:
        "samtools flagstat {input} > {output}"


rule target_qc:
    input:
        bam="results/align/{sample}.bam",
        bai="results/align/{sample}.bam.bai",
        bed=config["target_bed"],
        script="workflow/scripts/target_qc.sh",
    output:
        "results/qc/align/{sample}.target_qc.tsv",
    shell:
        "bash {input.script} {wildcards.sample} {input.bam} {input.bed} > {output}"


rule fastqc:
    input:
        "data/fastq/{sample}_{read}.fastq.gz",
    output:
        html="results/qc/fastqc/{sample}_{read}_fastqc.html",
        zip="results/qc/fastqc/{sample}_{read}_fastqc.zip",
    threads: 2
    shell:
        "fastqc -t {threads} -o results/qc/fastqc {input}"


rule multiqc:
    input:
        expand("results/qc/fastqc/{sample}_{read}_fastqc.zip", sample=SAMPLES, read=["R1", "R2"]),
        expand("results/qc/fastp/{sample}.json", sample=SAMPLES),
        expand("results/qc/align/{sample}.flagstat.txt", sample=SAMPLES),
    output:
        "results/qc/multiqc/multiqc_report.html",
    shell:
        "multiqc {input} -o results/qc/multiqc -f"

rule subset_bam:
    output:
        bam="data/{sample}.chr22.bam",
        bai="data/{sample}.chr22.bam.bai",
    params:
        url=lambda wc: config["samples"][wc.sample]["bam_url"],
        region=config["region"],
    shell:
        "samtools view -b -o {output.bam} '{params.url}' {params.region} && "
        "samtools index {output.bam}"


rule bam_to_fastq:
    input:
        "data/{sample}.chr22.bam",
    output:
        r1="data/fastq/{sample}_R1.fastq.gz",
        r2="data/fastq/{sample}_R2.fastq.gz",
        singletons="data/fastq/{sample}_singletons.fastq.gz",
    shell:
        "samtools collate -u -O {input} "
        "| samtools fastq -n -F 0x900 -1 {output.r1} -2 {output.r2} -0 /dev/null -s {output.singletons} -"